spring:
  datasource:
    password: ########
    url: jdbc:mysql://localhost:3306/work_anniversary_mail
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true 
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: manpreetkaur622495@gmail.com
    password: iarq yjfs kyhm lqca
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


          
